### ISSUE TITLE
Unable to wake from sleep

### ISSUE THREAD

**Issue by woeiwen** [xuandung38/thinkpad-lenovo-t440s-hackintosh#1]
Hi Xuandung,

First thank you for sharing your great work. I have the exact T440s setup as yours, except for higher RAM at 12 GB, 4300U HD4400. The main issue I have is that it can't wake it from sleep. Is. there any BIOs setting that needs to be changed?

Best,
WW

**Comment by xuandung38** [comment]
Please show your config bios
